PUT http://localhost:4000/api/user/address/:id 
Content-Type: application/json

{
    "_id": "60acb4fe981f9a2448ad7c42",
    "firstName": "Lisa",
    "lastName": "Marsvinstok",
    "phoneNumber": "123123123123",
    "address": "Marsvinsbyn 1",
    "zip": "12345",
    "city": "Guinea Pig City"
}

###

GET http://localhost:4000/api/user/address/:id 
Content-Type: application/json

{
    "_id": "60acb4fe981f9a2448ad7c42"
}

###

DELETE http://localhost:4000/api/user/address/:id 
Content-Type: application/json

{
    "_id": "60acb4fe981f9a2448ad7c42"
}

###