GET http://localhost:4000/api/categories

###

GET http://localhost:4000/api/category/:id
Content-Type: application/json

{
"_id": "60acf347b43d2849bd6ec0cd"
}

###

POST http://localhost:4000/api/categories 
Content-Type: application/json

{
"name": "kläder"
}

