###

GET http://localhost:4000/api/product/:id
Content-Type: application/json

{
    "_id": "60acae4ca5c1a830591e98e6"
}

###

GET http://localhost:4000/api/products
Content-Type: application/json

###

PUT http://localhost:4000/api/product/:id
Content-Type: application/json

{
    "_id": "60b407fdc3b69b2f34ef9064",
    "stock": "3000"
}

###

GET http://localhost:4000/api/products/categories 
Content-Type: application/json

###
GET http://localhost:4000/api/products/category 
Content-Type: application/json

###

POST http://localhost:4000/api/products
Content-Type: application/json

{
    "title": "Korv",
    "price": 5,
    "stock": 1000,
    "categories": ["mat"],
    "description": "OBS! Ej gjord av marsvin.",
    "img": "https://productimages.biltema.com/v1/image/imagebyfilename/49-388_xxl_1.jpg",
    "url": "korv"
}

###

DELETE  http://localhost:4000/api/product/60b4cbbc7129e600f4a7dd81

###