POST http://localhost:4000/upload
Content-Type: multipart/form-data; boundary=Row

--Row
Content-Disposition: form-data; name="file"; filename="lektalt.jpg"
Content-Type: image/jpeg

< ./lektalt.jpg
--Row--

###
POST http://localhost:4000/upload
Content-Type: multipart/form-data; boundary=Row

--Row
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--Row--

###

GET http://localhost:4000/api/upload/60b88696c142853abc1ddcb4